[OPENAI]
openai_api_key = ""

[LANGCHAIN]
LANGCHAIN_API_KEY = ""
LANGCHAIN_ENDPOINT = "https://api.smith.langchain.com"

[TAVILY]
TAVILY_API_KEY = ""

[GOOGLE]
google_api_key = ""

[ANTHROPIC]
anthropic_api_key = ""
